[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 12.0

